import Head from 'next/head'
import Link from 'next/link';
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [isActive,setisActive] = useState(false);
  const [isLink,setIsLink] = useState(false);
  const [isTut,setIsTut] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>ChainIDE|How to</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/chain.png" />
      </Head>
      <div >
      <nav className="w-full z-50 fixed inset-x-0 top-2 flex justify-center mt-0 items-center">
        <div className="w-full h-24 md:[100%] bg-navBar p-4 rounded-md flex items-center">
          <p className="text2xl md:text-4xl flex  text-slate-200 font-bold"><img className='w-6 md:w-9 h-6 md:h-9 bg-transparent' src="/chain.png"/>hainIDE|</p><span className=' text-slate-200  text-xl mr-5'>How To </span> 

          <div className="hidden md:ml-[250px]  md:flex items-center gap-6 flex-1">
            <Link href="/"><a className="text-textBase font-medium hover:text-slate-100 cursor-pointer duration-100 ease-in-out">Home</a></Link>
            <a className="text-textBase font-medium hover:text-slate-100 cursor-pointer duration-100 ease-in-out">
            <a href="#projects" onClick={() => setIsLink(!isLink)} className="text-textBase font-medium hover:text-slate-100 cursor-pointer duration-100 ease-in-out">Links</a>
            {isLink && (
              <div className=" w-275 h-340 bg-navBar rounded-lg fixed top-28 left-80 m-auto flex flex-col items-start justify-evenly gap-3">
                <a href="#projects" className="text-textBase font-medium hover:text-slate-100 cursor-pointer ml-5 duration-100 ease-in-out">ChainIDE</a>
                <a href="#contact" className="text-textBase font-medium hover:text-slate-100 cursor-pointer ml-5 duration-100 ease-in-out">Discord</a>
                <a href="#contact" className="text-textBase font-medium hover:text-slate-100 cursor-pointer ml-5 duration-100 ease-in-out">Twitter</a>
                <a href="#contact" className="text-textBase font-medium hover:text-slate-100 cursor-pointer ml-5 duration-100 ease-in-out">Telegram</a>
                <a href="#contact" className="text-textBase font-medium hover:text-slate-100 cursor-pointer ml-5 duration-100 ease-in-out">Github</a>
                <a href="#contact" className="text-textBase font-medium hover:text-slate-100 cursor-pointer ml-5 duration-100 ease-in-out">Docs</a>
              </div>
              )}

            </a>
            <a href="#projects" className="text-textBase font-medium hover:text-slate-100 cursor-pointer duration-100 ease-in-out">
            <a href="#projects" onClick={() => setIsTut(!isTut)} className="text-textBase font-medium hover:text-slate-100 cursor-pointer duration-100 ease-in-out">Getting Started</a>
            {isTut && (
              <div className=" w-275 h-420 bg-navBar rounded-lg fixed top-28 right-55 m-auto flex flex-col items-start justify-evenly gap-5">
                <a href="#projects" className="text-textBase font-medium hover:text-slate-100 ml-5 cursor-pointer duration-100 ease-in-out">ChainIDE Introduction</a>
                <a href="#contact" className="text-textBase font-medium hover:text-slate-100 ml-5 cursor-pointer duration-100 ease-in-out">Enviroment Setup</a>
                <a href="#contact" className="text-textBase font-medium hover:text-slate-100 ml-5 cursor-pointer duration-100 ease-in-out">Wallet Configuration</a>
                <a href="#contact" className="text-textBase font-medium hover:text-slate-100 ml-5 cursor-pointer duration-100 ease-in-out">ChainIDE Modules</a>
                <a href="#contact" className="text-textBase font-medium hover:text-slate-100 ml-5 cursor-pointer duration-100 ease-in-out">Loading Your Network</a>
                <a href="#contact" className="text-textBase font-medium hover:text-slate-100 ml-5 cursor-pointer duration-100 ease-in-out">Saving Your Work</a>
                <a href="#contact" className="text-textBase font-medium hover:text-slate-100 ml-5 cursor-pointer duration-100 ease-in-out">Port Forwading</a>
              </div>
              )}
            </a>
            <Link href="/tutorials"><a className="text-textBase font-medium hover:text-slate-100 cursor-pointer duration-100 ease-in-out">Tutorials</a></Link>
            <Link href="/contact"><a className="text-textBase font-medium hover:text-slate-100 cursor-pointer duration-100 ease-in-out">Contact</a></Link>
          </div>
          <div  className="block md:hidden ml-auto cursor-pointer" onClick={()=> setisActive(!isActive)}>
            cg
          </div>

          {isActive && (
            <div className=" w-370 h-510 bg-navBar rounded-lg fixed top-28 m-auto flex flex-col items-start justify-evenly gap-5">
              <a href="" onClick={() => setisActive(false)} className="text-textBase font-medium ml-6 hover:text-slate-100 cursor-pointer duration-100 ease-in-out">Home</a>
              <a href="" onClick={() => setisActive(false)} className="text-textBase font-medium ml-6 hover:text-slate-100 cursor-pointer duration-100 ease-in-out">Links</a>
              <a href="" onClick={() => setisActive(false)} className="text-textBase font-medium ml-6 hover:text-slate-100 cursor-pointer duration-100 ease-in-out">Getting Started</a>
              <a href="" onClick={() => setisActive(false)} className="text-textBase font-medium ml-6 hover:text-slate-100 cursor-pointer duration-100 ease-in-out">Tutorials</a>
              <a href="" onClick={() => setisActive(false)} className="text-textBase font-medium ml-6 hover:text-slate-100 cursor-pointer duration-100 ease-in-out">Contact</a>
            </div>
          )}
        </div>
      </nav>
      <main className="w-[90%] ml-auto mr-auto mt-7 relative md:mt-5">
        <div className="w-full h-[200px] md:h-340 md:flex flex-col items-center justify-center">
            <p className="text-2xl md:text-6xl text-white mt-auto text-center">
              A Cloud-Based Multi-Blockchain IDE.
            </p>
            
        </div>
        <div className="w-full h-80 md:flex flex-col items-center justify-center">
            <p className="text-xl text-white mt-auto text-center">
              Swift, Simple, Smart.
            </p>
        </div>
        <div className='w-full h-72'></div>
        </main>

        
      </div>

    
    </div>
  )
}
