import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

function intro() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ChainIDE|Introduction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/chain.png" />
      </Head>
      <div className="w-[80%]  ml-auto mr-auto mt-7 relative md:mt-5">
        <div className="w-full flex flex-col items-center justify-center">
            <p className="text-2xl md:text-6xl text-white mt-5 text-center">
               ChainIDE Introduction
            </p>
        </div>
        <div className='w-full h-56'></div>
        <div className="md:w-[90%] w-full mb-20 ml-auto mr-auto h-320 md:h-80 md:flex flex-col items-center justify-center">
           <p className="text-sm md:text-xl text-white text-center">
           ChainIDE is an cloud-based IDE for creating decentralized applications to deploy on different blockchains such as Ethereum, BNB Chain, Polygon, Conflux, Nervos, Dfinity, Flow, Chain33, Fisco Bcos, etc. It fasts the development cycle and has pre-installed plugins that save users' time and effort. ChainIDE is the world's most commonly used IDE, due to its interactive interface and easy-to-use attributes among other attributes that have attracted developers, practitioners, and researchers from all around the world. It provides a complete and ready-to-use environment for smart contract development as well as provides detailed documentation for learning purposes. ChainIDE is a powerful open-source cloud-based IDE that helps you write smart contracts in different programming languages and for different blockchains. It has modules for writing, compiling, debugging, testing, deploying a smart contract,  and much more.
           </p>
        </div>
        <div className='w-full h-56'></div>
        <div className="border border-zinc-800 rounded-md p-2 min-w-[300px] h-360 md:max-w-[90%] ml-auto mr-auto relative hover:border-zinc-600 duration-100 ease-in-out">
          <img src="chain11.png" alt="" className="w-full h-360 object-cover rounded-md my-4"/>
        </div>
        <div className='w-full h-56'></div>
        <div className="md:w-[90%] w-full mb-20 ml-auto mr-auto h-320 md:h-80 md:flex flex-col items-center justify-center">
           <h1>Why ChainIDE</h1>
           <p className="text-sm md:text-xl text-white text-center">
           ChainIDE combines the simplicity of a source code editor with powerful developer tooling, like IntelliSense code completion and debugging. First and foremost, it is an editor that gets out of your way. The delightfully frictionless edit-build-debug cycle means less time fiddling with your environment, and more time executing your ideas. ChainIDE is a cloud-based multi-chain IDE that can be easily switched to different smart chains with only one click. It supports a multi-chain online IDE development environment. The environment supported by ChainIDE includes Facebook Diem, Ethereum, BNB Chain, Conflux, Dfinity, Nervos, Polygon, Flow, Chain 33, AntFinancial OpenChain, Fisco Bcos, Iost and Filoop. It has been used by developers in more than 120 countries, and more than 3.5 million contracts have been compiled at the same time. 
           </p>
        </div>
      </div>

    </div>
  )
}

export default intro