import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from 'react'

function setup() {
  return (
  <div className={styles.container}>
    <Head>
      <title>ChainIDE|Introduction</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/chain.png" />
    </Head>
    <div className="w-[90%] h-420 ml-auto mr-auto mt-7 relative md:mt-5 bg-white">

    </div>

  </div>
  )
}

export default setup